"""
PR writer for the deviation detector.

Takes adapted SQL models from detector.py and opens a GitHub pull request
against the dev branch. The PR is labelled 'tenant_model' (Category 2).

Permitted: open PR against dev.
Prohibited: merge PR, push to staging or main, execute SQL.
"""

from __future__ import annotations

import logging
import os
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

REPO = os.environ.get("GITHUB_REPO", "rfim/multi-tenant-onboarding")
SIMULATE = os.environ.get("SIMULATE", "0") == "1"


def open_pr(tenant_id: str, models: dict[str, str], deviation_summary: str) -> str:
    """
    Creates a branch, writes adapted SQL files, and opens a GitHub PR.

    When SIMULATE=1 (or no GITHUB_TOKEN), writes files locally and returns
    a placeholder URL so the test can proceed without a live GitHub token.

    Args:
        tenant_id: the tenant being onboarded
        models: dict mapping filename -> sql_content
        deviation_summary: plain-language description of deviations

    Returns:
        The URL of the opened PR (or a local path in simulate mode).
    """
    branch_name = f"onboard/{tenant_id}/adapted-silver-{_timestamp()}"

    logger.info(
        "Opening deviation PR for tenant %s on branch %s (%d models)",
        tenant_id, branch_name, len(models),
    )

    if SIMULATE or not os.environ.get("GITHUB_TOKEN"):
        return _open_pr_simulated(tenant_id, branch_name, models, deviation_summary)

    return _open_pr_real(tenant_id, branch_name, models, deviation_summary)


def _open_pr_simulated(
    tenant_id: str,
    branch_name: str,
    models: dict[str, str],
    deviation_summary: str,
) -> str:
    """
    Writes adapted SQL files to a temp directory and returns a local path.
    Used when SIMULATE=1 or GITHUB_TOKEN is absent (test environments).
    """
    out_dir = Path(tempfile.mkdtemp(prefix=f"deviation_pr_{tenant_id}_"))
    for filename, sql in models.items():
        dest = out_dir / Path(filename).name
        dest.write_text(sql)
        logger.info("[simulate] Wrote %s (%d bytes)", dest, len(sql))

    pr_body_path = out_dir / "PR_BODY.md"
    pr_body_path.write_text(_build_pr_body(tenant_id, models, deviation_summary))

    logger.info("[simulate] PR body written to %s", pr_body_path)
    logger.info("[simulate] Branch would be: %s", branch_name)
    return f"file://{out_dir}  (simulated — set GITHUB_TOKEN for a real PR)"


def _open_pr_real(
    tenant_id: str,
    branch_name: str,
    models: dict[str, str],
    deviation_summary: str,
) -> str:
    """
    Creates a git branch, commits adapted SQL files, and opens a GitHub PR
    via the gh CLI. Requires GITHUB_TOKEN in the environment.
    """
    repo_root = Path(__file__).parents[2]

    # Write model files into the working tree
    for filename, sql in models.items():
        dest = repo_root / "dbt" / "models" / "silver" / tenant_id / Path(filename).name
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(sql)
        logger.info("Wrote %s", dest.relative_to(repo_root))

    # Create branch, stage, and commit
    _git(repo_root, "checkout", "-b", branch_name)
    _git(repo_root, "add", f"dbt/models/silver/{tenant_id}/")
    _git(repo_root, "commit", "-m", f"[deviation] {tenant_id}: adapted Silver models")
    _git(repo_root, "push", "-u", "origin", branch_name)

    # Open PR via gh CLI
    body = _build_pr_body(tenant_id, models, deviation_summary)
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", REPO,
            "--base", "dev",
            "--head", branch_name,
            "--title", f"[deviation] {tenant_id} adapted Silver models",
            "--body", body,
            "--label", "tenant_model",
            "--label", "deviation-detected",
            "--label", "needs-review",
            "--draft",
        ],
        capture_output=True,
        text=True,
        check=True,
        cwd=str(repo_root),
    )
    pr_url = result.stdout.strip()
    logger.info("PR opened: %s", pr_url)
    return pr_url


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git"] + list(args), cwd=str(cwd), check=True)


def _build_pr_body(tenant_id: str, models: dict[str, str], deviation_summary: str) -> str:
    file_list = "\n".join(f"- `{f}`" for f in models)
    return f"""## Adapted Silver models for `{tenant_id}`

**Generated by:** deviation_detector agent
**Human review required:** yes
**Change category:** tenant_model (Category 2, 24h SLA)
**Confidence:** see agent output below

### Deviations detected

{deviation_summary}

### Files changed

{file_list}

### Review checklist

- [ ] Confirm the extra fields are expected for this customer's source system
- [ ] Confirm CAST logic is correct for any type-mismatched fields
- [ ] Confirm NULL placeholders for missing fields are intentional
- [ ] Run `dbt compile --select silver_{tenant_id}*` and verify no compilation errors
- [ ] Ensure the Silver DQ contract in `dq/expectations/{tenant_id}/silver_contract.yml`
      includes expectations for any new fields

### What this PR does not do

This PR does not modify shared Bronze or Silver tables. It adds a tenant-specific
adapted model. No existing tenant is affected.
"""


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
