"""
PR writer for the deviation detector.

Takes adapted SQL models from detector.py and opens a GitHub pull request
against the dev branch. The PR is labelled 'tenant_model' (Category 2).

Permitted: open PR against dev.
Prohibited: merge PR, push to staging or main, execute SQL.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def open_pr(tenant_id: str, models: dict[str, str], deviation_summary: str) -> str:
    """
    Creates a branch and opens a PR with the adapted Silver models.

    Args:
        tenant_id: the tenant being onboarded
        models: dict mapping filename -> sql_content from detector.generate_adapted_models()
        deviation_summary: plain-language description of the deviations found

    Returns:
        The URL of the opened PR.
    """
    branch_name = f"onboard/{tenant_id}/adapted-silver-{_timestamp()}"

    logger.info(
        "Opening deviation PR for tenant %s on branch %s (%d models)",
        tenant_id, branch_name, len(models),
    )

    # TODO: implement via PyGithub or GitHub REST API
    # 1. Create branch from dev HEAD
    # 2. For each model in models: write to dbt/models/silver/<tenant_id>/<filename>
    # 3. Open PR with:
    #    title: "[deviation] <tenant_id> adapted Silver models"
    #    body: _build_pr_body(tenant_id, models, deviation_summary)
    #    base: dev
    #    labels: ["tenant_model", "deviation-detected", "needs-review"]
    #    assignees: [] (promotion_classifier will suggest reviewers)
    # 4. Return PR URL

    raise NotImplementedError("open_pr not yet implemented")


def _build_pr_body(tenant_id: str, models: dict[str, str], deviation_summary: str) -> str:
    file_list = "\n".join(f"- `{f}`" for f in models)
    return f"""## Adapted Silver models for `{tenant_id}`

**Generated by:** deviation_detector agent
**Human review required:** yes
**Change category:** tenant_model (Category 2, 24h SLA)
**Confidence:** see agent output below

### Deviations detected

{deviation_summary}

### Files changed

{file_list}

### Review checklist

- [ ] Confirm the extra fields are expected for this customer's source system
- [ ] Confirm CAST logic is correct for any type-mismatched fields
- [ ] Confirm NULL placeholders for missing fields are intentional
- [ ] Run `dbt compile --select silver_{tenant_id}*` and verify no compilation errors
- [ ] Ensure the Silver DQ contract in `dq/expectations/{tenant_id}/silver_contract.yml`
      includes expectations for any new fields

### What this PR does not do

This PR does not modify shared Bronze or Silver tables. It adds a tenant-specific
adapted model. No existing tenant is affected.
"""


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
